# Generated by Django 5.1.5 on 2025-08-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
